#!/usr/bin/env bash
#
# Rebuild the `npm-package-react` branch from packages/react.
#
# npm git dependencies always install the *root* package of a repo, and npm has
# no subdirectory syntax for git URLs. Pointing a consumer at zen-ui directly
# therefore resolves to @algorisys/zen-ui-workspace — private, no dist — rather
# than the React binding. This script lays the built React package out at the
# root of an orphan branch so consumers can do:
#
#   "@algorisys/zen-ui-react": "git@github.com:Algorisys-Technologies/zen-ui.git#npm-package-react"
#
# Same shape react-excel uses on its feat-npm-package branch.
#
# Usage:  bash scripts/pack-branch.sh [--push]
#
set -euo pipefail

BRANCH=npm-package-react
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

cd "$ROOT"
SRC_COMMIT="$(git rev-parse HEAD)"

echo "==> building packages/react"
( cd packages/react && bun run build:lib )

echo "==> staging package at $STAGE"
cp -r packages/react/dist "$STAGE/dist"
# A branch keeps every release's blobs forever and the sourcemaps are the bulk
# of dist (8 of 13 MB). They aid debugging into the library, nothing more.
find "$STAGE/dist" -name '*.map' -delete
cp packages/react/package.json "$STAGE/package.json"
cp LICENSE COMMERCIAL.md AGENTS.md "$STAGE/"
cp -r skills "$STAGE/skills"

echo "==> rewriting package.json for git-dependency install"
node -e '
const fs = require("fs");
const [file, commit] = process.argv.slice(1);
const p = JSON.parse(fs.readFileSync(file, "utf8"));
// devDependencies use the workspace: protocol, which npm cannot resolve when
// installing from git.
delete p.devDependencies;
// dist is committed, so there is nothing to build. Leaving scripts in place
// would give npm a prepare script and it would try.
delete p.scripts;
delete p.publishConfig;
p.zenUiSourceCommit = commit;
fs.writeFileSync(file, JSON.stringify(p, null, 2) + "\n");
' "$STAGE/package.json" "$SRC_COMMIT"

echo "==> committing $BRANCH"
cd "$STAGE"
git init -q -b "$BRANCH"
git config user.name  "$(cd "$ROOT" && git config user.name)"
git config user.email "$(cd "$ROOT" && git config user.email)"
git add -A
git commit -q -m "build(react): package @algorisys/zen-ui-react from ${SRC_COMMIT:0:12}

Generated by scripts/pack-branch.sh — do not hand-edit. Rebuild instead."

cd "$ROOT"
git fetch -q "$STAGE" "$BRANCH:$BRANCH" --force
echo "==> local branch $BRANCH now at $(git rev-parse --short "$BRANCH")"

if [ "${1:-}" = "--push" ]; then
  echo "==> pushing"
  git push --force origin "$BRANCH"
else
  echo "==> not pushed. Review it, then: git push --force origin $BRANCH"
fi
